import { TTheme } from './TTheme';

export const theme: TTheme = {
  colors: {
    default: {
      surface: '#FFFFFF',
      accent: '#C4F500',
      accentHover: '#B4E000',
      accentBorder: '#C7DF87',
      accentSurface: '#F5FBDD',
      focus: '#587516',
      danger: '#B4232C',
      dangerSurface: '#FFF1F2',
      disabledBg: '#EEF1F4',
      bg: '#F4F7F9',
      primary: '#1B3A4B',
      primaryText: '#1B3A4B',
      secondaryText: '#6B7C86',
      border: '#D9E1E5',
      grey: '#8A9AA3',
      lightBlue: '#DCECF5',
      lightPink: '#F7E1E7',
      yellow: '#F7E7A8',
      lightGreen: '#DDEFE5',
    },

    light: {
      surface: '#FFFFFF',
      accent: '#C4F500',
      accentHover: '#B4E000',
      accentBorder: '#C7DF87',
      accentSurface: '#F5FBDD',
      focus: '#587516',
      danger: '#B4232C',
      dangerSurface: '#FFF1F2',
      disabledBg: '#EEF1F4',
      bg: '#F4F7F9',
      primary: '#1B3A4B',
      primaryText: '#1B3A4B',
      secondaryText: '#6B7C86',
      border: '#D9E1E5',
      grey: '#8A9AA3',
      lightBlue: '#DCECF5',
      lightPink: '#F7E1E7',
      yellow: '#F7E7A8',
      lightGreen: '#DDEFE5',
    },

    dark: {
      surface: '#FFFFFF',
      accent: '#C4F500',
      accentHover: '#B4E000',
      accentBorder: '#C7DF87',
      accentSurface: '#F5FBDD',
      focus: '#587516',
      danger: '#B4232C',
      dangerSurface: '#FFF1F2',
      disabledBg: '#EEF1F4',
      bg: '#F4F7F9',
      primary: '#1B3A4B',
      primaryText: '#1B3A4B',
      secondaryText: '#6B7C86',
      border: '#D9E1E5',
      grey: '#8A9AA3',
      lightBlue: '#DCECF5',
      lightPink: '#F7E1E7',
      yellow: '#F7E7A8',
      lightGreen: '#DDEFE5',
    },
  },
};